export const testInstitutions = [
  {
    name: "FinBank",
    id: "finbank",
    keywords: ["finbank", "finicity"],
    logo: "https://prod-carpintero-branding.s3.us-west-2.amazonaws.com/102105/icon.svg",
    url: "http://www.finbank.com",
    is_test_bank: true,
    routing_numbers: [],
    finicity: {
      id: "101732",
      supports_aggregation: true,
      supports_history: false,
      supports_identification: true,
      supports_oauth: true,
      supports_verification: true,
      supportsRewards: false,
      supportsBalance: true,
    },
  },
  {
    name: "FinBank C",
    id: "finbankC",
    keywords: ["finbank", "finicity"],
    logo: "https://prod-carpintero-branding.s3.us-west-2.amazonaws.com/102105/icon.svg",
    url: "http://www.finbank.com",
    is_test_bank: true,
    routing_numbers: [],
    finicity: {
      id: "170680",
      supports_aggregation: true,
      supports_history: false,
      supports_identification: false,
      supports_oauth: true,
      supports_verification: false,
      supportsRewards: false,
      supportsBalance: false,
    },
  },
  {
    name: "Finbank Oauth Billable",
    id: "finbankOauthBillable",
    keywords: ["finbank", "finicity"],
    logo: "https://prod-carpintero-branding.s3.us-west-2.amazonaws.com/102105/icon.svg",
    url: "http://www.finbank.com",
    is_test_bank: true,
    routing_numbers: [],
    finicity: {
      id: "171011",
      supports_aggregation: true,
      supports_history: true,
      supports_identification: true,
      supports_oauth: true,
      supports_verification: true,
      supportsRewards: false,
      supportsBalance: false,
    },
  },
  {
    name: "FinBank M1",
    id: "finbankM1",
    keywords: ["finbank", "finicity"],
    logo: "https://prod-carpintero-branding.s3.us-west-2.amazonaws.com/102105/icon.svg",
    url: "http://www.finbank.com",
    is_test_bank: true,
    routing_numbers: [],
    finicity: {
      id: "170830",
      supports_aggregation: true,
      supports_history: true,
      supports_identification: true,
      supports_oauth: true,
      supports_verification: true,
      supportsRewards: false,
      supportsBalance: false,
    },
  },
  {
    name: "FinBank O",
    id: "finbankO",
    keywords: ["finbank", "finicity"],
    logo: "https://prod-carpintero-branding.s3.us-west-2.amazonaws.com/102105/icon.svg",
    url: "http://www.finbank.com",
    is_test_bank: true,
    routing_numbers: [],
    finicity: {
      id: "102219",
      supports_aggregation: true,
      supports_history: false,
      supports_identification: false,
      supports_oauth: true,
      supports_verification: false,
      supportsRewards: false,
      supportsBalance: false,
    },
  },
  {
    name: "FinBank Decertified",
    id: "finbankDecertified",
    keywords: ["finbank", "finicity"],
    logo: "https://prod-carpintero-branding.s3.us-west-2.amazonaws.com/102105/icon.svg",
    url: "http://www.finbank.com",
    is_test_bank: true,
    routing_numbers: [],
    finicity: {
      id: "176082",
      supports_aggregation: true,
      supports_history: false,
      supports_identification: true,
      supports_oauth: true,
      supports_verification: false,
      supportsRewards: false,
      supportsBalance: false,
    },
  },
  {
    name: "FinBank Offline",
    id: "finbankOffline",
    keywords: ["finbank", "finicity"],
    logo: "https://prod-carpintero-branding.s3.us-west-2.amazonaws.com/102105/icon.svg",
    url: "http://www.finbank.com",
    is_test_bank: true,
    routing_numbers: [],
    finicity: {
      id: "176078",
      supports_aggregation: true,
      supports_history: false,
      supports_identification: false,
      supports_oauth: true,
      supports_verification: false,
      supportsRewards: false,
      supportsBalance: false,
    },
  },
  {
    name: "FinBank Billable",
    id: "finbankBillable",
    keywords: ["finbank", "finicity"],
    logo: "https://prod-carpintero-branding.s3.us-west-2.amazonaws.com/102105/icon.svg",
    url: "http://www.finbank.com",
    is_test_bank: true,
    routing_numbers: [],
    finicity: {
      id: "170776",
      supports_aggregation: true,
      supports_history: true,
      supports_identification: true,
      supports_oauth: true,
      supports_verification: true,
      supportsRewards: false,
      supportsBalance: false,
    },
  },
  {
    name: "Health Check",
    id: "healthCheck",
    keywords: ["finbank", "finicity"],
    logo: "https://prod-carpintero-branding.s3.us-west-2.amazonaws.com/102105/icon.svg",
    url: "http://www.finbank.com",
    is_test_bank: true,
    routing_numbers: [],
    finicity: {
      id: "102220",
      supports_aggregation: true,
      supports_history: false,
      supports_identification: false,
      supports_oauth: true,
      supports_verification: false,
      supportsRewards: false,
      supportsBalance: false,
    },
  },
  {
    name: "FinBank Profiles - C",
    id: "finbankProfilesC",
    keywords: ["finbank", "finicity"],
    logo: "https://prod-carpintero-branding.s3.us-west-2.amazonaws.com/102105/icon.svg",
    url: "http://www.finbank.com",
    is_test_bank: true,
    routing_numbers: [],
    finicity: {
      id: "199100",
      supports_aggregation: true,
      supports_history: false,
      supports_identification: false,
      supports_oauth: true,
      supports_verification: true,
      supportsRewards: false,
      supportsBalance: false,
    },
  },
  {
    name: "FinBank Profiles J",
    id: "finbankProfilesJ",
    keywords: ["finbank", "finicity"],
    logo: "https://prod-carpintero-branding.s3.us-west-2.amazonaws.com/102105/icon.svg",
    url: "http://www.finbank.com",
    is_test_bank: true,
    routing_numbers: [],
    finicity: {
      id: "176081",
      supports_aggregation: true,
      supports_history: false,
      supports_identification: false,
      supports_oauth: true,
      supports_verification: false,
      supportsRewards: false,
      supportsBalance: false,
    },
  },
  {
    name: "FinBank Profiles - B",
    id: "finbankProfilesB",
    keywords: ["finbank", "finicity"],
    logo: "https://prod-carpintero-branding.s3.us-west-2.amazonaws.com/102105/icon.svg",
    url: "http://www.finbank.com",
    is_test_bank: true,
    routing_numbers: [],
    finicity: {
      id: "102168",
      supports_aggregation: true,
      supports_history: false,
      supports_identification: true,
      supports_oauth: true,
      supports_verification: true,
      supportsRewards: false,
      supportsBalance: false,
    },
  },
  {
    name: "FinBank Profiles - A",
    id: "finbankProfilesA",
    keywords: ["finbank", "finicity"],
    logo: "https://prod-carpintero-branding.s3.us-west-2.amazonaws.com/102105/icon.svg",
    url: "http://www.finbank.com",
    is_test_bank: true,
    routing_numbers: [],
    finicity: {
      id: "102105",
      supports_aggregation: true,
      supports_history: false,
      supports_identification: true,
      supports_oauth: true,
      supports_verification: true,
      supportsRewards: false,
      supportsBalance: false,
    },
  },
];
