version: '3.8'

services:

  server:
    depends_on: [cache, ui]
    container_name: ucw-app-server
    restart: on-failure
    build: .
    image: universalconnectfoundation/ucw-app:v0.0.1
    networks:
      - ucw
    ports:
      - '8080:8080'
    env_file:
      - .env
    environment:
      RedisServer: "redis://cache:6379"
      ResourcePrefix: "http://ui:5173"

  ui:
    container_name: ucw-app-ui
    restart: on-failure
    build: ./ui
    image: universalconnectfoundation/ucw-ui:v0.0.1
    networks:
      - ucw
    ports:
      - '5173:5173'

  cache:
    container_name: ucw-app-cache
    image: redis:7.2-alpine
    restart: on-failure
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
    networks:
      - ucw
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data

volumes:
  cache:
    driver: local

networks:
  ucw: