export const testInstitutions = [
  {
    name: "MX Bank",
    id: "mxBank",
    keywords: ["Gringotts", "MX Bank"],
    logo: "https://content.moneydesktop.com/storage/MD_Assets/Ipad%20Logos/100x100/INS-3aeb38da-26e4-3818-e0fa-673315ab7754_100x100.png",
    url: "https://mx.com",
    is_test_bank: true,
    routing_numbers: [],
    mx: {
      id: "mxbank",
      supports_aggregation: true,
      supports_history: true,
      supports_identification: true,
      supports_oauth: false,
      supports_verification: true,
      supportsRewards: false,
      supportsBalance: false,
    },
  },
  {
    name: "MX Bank (Oauth)",
    id: "mxBankOauth",
    keywords: ["Gringotts", "MX Bank", "oauth"],
    logo: "https://s3.amazonaws.com/MD_Assets/Ipad%20Logos/100x100/INS-3aeb38da-26e4-3818-e0fa-673315ab7754_100x100.png",
    url: "https://mx.com",
    is_test_bank: true,
    routing_numbers: [],
    mx: {
      id: "mx_bank_oauth",
      supports_aggregation: true,
      supports_history: false,
      supports_identification: true,
      supports_oauth: true,
      supports_verification: true,
      supportsRewards: false,
      supportsBalance: false,
    },
  },
  {
    name: "MXCU (OAuth)",
    id: "mxCUOauth",
    keywords: ["oauth"],
    logo: null,
    url: "https://mxcu.mx.com",
    is_test_bank: true,
    routing_numbers: [],
    mx: {
      id: "mxcu_oauth",
      supports_aggregation: true,
      supports_history: false,
      supports_identification: true,
      supports_oauth: true,
      supports_verification: true,
      supportsRewards: false,
      supportsBalance: false,
    },
  },
  {
    name: "MXCU (Credential)",
    id: "mxCuCredential",
    keywords: [],
    logo: null,
    url: "https://mxcu.mx.com",
    is_test_bank: true,
    routing_numbers: [],
    mx: {
      id: "mxcu_credential",
      supports_aggregation: true,
      supports_history: true,
      supports_identification: true,
      supports_oauth: false,
      supports_verification: true,
      supportsRewards: false,
      supportsBalance: false,
    },
  },
];
