import type { CachedInstitution } from "@repo/utils";
import { testInstitutions as mxTestInstitutions } from "@repo/mx-adapter";
import { testInstitutions as finicityTestInstitutions } from "@repo/finicity-adapter";
import { testInstitutions as sophtronTestInstitutions } from "@repo/sophtron-adapter";
import { testInstitutions as akoyaTestInstitutions } from "@repo/akoya-adapter";

export const testChaseBankToFilter: CachedInstitution = {
  name: "Chase Bank Test Filter",
  id: "prodTestBankFilter",
  keywords: ["test"],
  logo: "https://universalconnectproject.org/images/ucp-logo-icon.svg",
  url: "",
  is_test_bank: true,
  routing_numbers: [],
  mx: {
    id: "test",
    supports_aggregation: true,
    supports_history: true,
    supports_identification: true,
    supports_oauth: true,
    supports_verification: true,
    supportsRewards: false,
    supportsBalance: false,
  },
};

const buildTestInstitutions = (testInstitutions: CachedInstitution[][]) =>
  testInstitutions.reduce(
    (acc, institutions) => [
      ...acc,
      ...institutions.map((institution) => ({
        ...institution,
        is_test_bank: true,
      })),
    ],
    [],
  );

export const testInstitutions = buildTestInstitutions([
  mxTestInstitutions,
  finicityTestInstitutions,
  sophtronTestInstitutions,
  akoyaTestInstitutions,
  [testChaseBankToFilter],
  [
    {
      name: "TestExampleOauth Bank",
      id: "3258fb11-bffe-4501-90d6-3b8d35f746e9",
      keywords: ["test", "example", "oauth"],
      logo: "https://universalconnectproject.org/images/ucp-logo-icon.svg",
      url: "https://test-example.com",
      is_test_bank: true,
      routing_numbers: [],
      testExampleA: {
        id: "testExampleAOauth",
        supports_aggregation: true,
        supports_history: true,
        supports_identification: true,
        supports_oauth: true,
        supports_verification: true,
        supportsRewards: false,
        supportsBalance: false,
      },
    },
    {
      name: "TestExampleFailedOauth Bank",
      id: "a1b81454-10c9-4061-8294-370e300c83e8",
      keywords: ["test", "example", "oauth"],
      logo: "https://universalconnectproject.org/images/ucp-logo-icon.svg",
      url: "https://test-example.com",
      is_test_bank: true,
      routing_numbers: [],
      testExampleA: {
        id: "testExampleAOauthFailed",
        supports_aggregation: true,
        supports_history: true,
        supports_identification: true,
        supports_oauth: true,
        supports_verification: true,
        supportsRewards: false,
        supportsBalance: false,
      },
    },
    {
      name: "All Aggregators Bank",
      id: "3b561893-e969-4a2c-9e58-3b81b203cdc1",
      keywords: ["Gringotts", "MX Bank", "oauth"],
      logo: "https://universalconnectproject.org/images/ucp-logo-icon.svg",
      url: "https://universalconnectproject.org/",
      is_test_bank: true,
      routing_numbers: [],
      finicity: {
        id: "fake",
        supports_aggregation: true,
        supports_history: false,
        supports_identification: true,
        supports_oauth: true,
        supports_verification: true,
        supportsRewards: false,
        supportsBalance: false,
      },
    },
    {
      name: "TestExampleA Bank",
      id: "5e498f60-3496-4299-96ed-f8eb328ae8af",
      keywords: ["test", "example", "tex"],
      logo: "https://universalconnectproject.org/images/ucp-logo-icon.svg",
      url: "https://test-example.com",
      is_test_bank: true,
      routing_numbers: [],
      testExampleA: {
        id: "testExampleA",
        supports_aggregation: true,
        supports_history: true,
        supports_identification: true,
        supports_oauth: true,
        supports_verification: true,
        supportsRewards: false,
        supportsBalance: false,
      },
    },
    {
      name: "TestExampleB Bank",
      id: "aeab64a9-7a78-4c5f-bd27-687f3c8b8492",
      keywords: ["test", "example", "tex"],
      logo: "https://universalconnectproject.org/images/ucp-logo-icon.svg",
      url: "https://test-example.com",
      is_test_bank: true,
      routing_numbers: ["111111111"],
      testExampleB: {
        id: "testExampleB",
        supports_aggregation: true,
        supports_history: true,
        supports_identification: true,
        supports_oauth: true,
        supports_verification: true,
        supportsRewards: false,
        supportsBalance: false,
      },
    },
    {
      name: "TestExample Doesnt Support Verification Bank",
      id: "d20bf4b6-ca19-41c6-a3f8-79801fab379b",
      keywords: ["test", "example"],
      logo: "https://universalconnectproject.org/images/ucp-logo-icon.svg",
      url: "https://test-example.com",
      is_test_bank: true,
      routing_numbers: [],
      testExampleB: {
        id: "testExampleB",
        supports_aggregation: true,
        supports_history: true,
        supports_identification: true,
        supports_oauth: true,
        supports_verification: false,
        supportsRewards: false,
        supportsBalance: false,
      },
    },
    {
      name: "TestExample Doesnt Support Identification Bank",
      id: "4c1b2595-a5aa-41a1-a2c6-f6caa1e226a6",
      keywords: ["test", "example"],
      logo: "https://universalconnectproject.org/images/ucp-logo-icon.svg",
      url: "https://test-example.com",
      is_test_bank: true,
      routing_numbers: [],
      testExampleB: {
        id: "testExampleB",
        supports_aggregation: true,
        supports_history: true,
        supports_identification: false,
        supports_oauth: true,
        supports_verification: true,
        supportsRewards: false,
        supportsBalance: false,
      },
    },
    {
      name: "TestExample Bank To Hide",
      id: "7a909e62-98b6-4a34-8725-b2a6a63e830a",
      keywords: ["test", "example"],
      logo: "https://universalconnectproject.org/images/ucp-logo-icon.svg",
      url: "https://test-example.com",
      is_test_bank: true,
      routing_numbers: [],
      testExampleA: {
        id: "testExampleA",
        supports_aggregation: true,
        supports_history: true,
        supports_identification: true,
        supports_oauth: true,
        supports_verification: true,
        supportsRewards: false,
        supportsBalance: false,
      },
      testExampleB: {
        id: "testExampleB",
        supports_aggregation: true,
        supports_history: true,
        supports_identification: true,
        supports_oauth: true,
        supports_verification: true,
        supportsRewards: false,
        supportsBalance: false,
      },
    },
  ],
]);
