name: NPM Audit Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/Iron"

      - name: Install dependencies
        run: npm ci

      - name: Run npm audit for high or critical vulnerabilities
        run: npm audit --audit-level=high
